### PR TITLE
Fix filters deactivated after auto-reopen

### LINKED ISSUE #108: auto_reopen is great, but it loses any applied filters and there is no indication that a reopen occured
So, auto_reopen is a great addition for dealing with the memory leak in libsystemd (good job systemd guys).
However, I have applied some filters because I don't want ALL the journal entries.   But, when the code in `with_auto_retry` decides to close and re-open the journal, those filters are lost.   There is also no indication to the caller that this occurred and they may need to re-apply the filters.   Also, the @sd_call_count is not even exported in any way so that the caller could determine that a re-open may have happened by watching the count.

Instead, as the caller/user of this gem, I have had to just open the journal with auto_reopen: false and then do the occasional close at the user level.

- Ideas that would help: perhaps do a better job of saving the actual state of the journal besides just remembering the cursor.
- Re-tool `with_auto_reopen` so that it instead raises an exception (perhaps something like `JournalReOpened`) so the user can then re-setup any filters

Note: I have implemented a work-around, so priority is not urgent or even high.   But, some more thought definitely needs to be put into the whole auto_reopen solution to libsystemd's memory problem.

Thanks!

### PR DESCRIPTION
**Pull request by Watson1978**
Fix #108

I have improved memory usage at https://github.com/ledbettj/systemd-journal/pull/103
The filter conditions were not handled in auto-reopen operation, so they were cleared by initialization at
https://github.com/ledbettj/systemd-journal/blob/d154b198535b9d20e4b08397bb946e31e1c2be25/lib/systemd/journal/navigable.rb#L143

In this PR, it will restore the filter conditions after auto reopen journal.

### CODE REVIEW

File: lib/systemd/journal/navigable.rb [hunk 1]
```diff
@@ -137,11 +137,21 @@ def with_auto_reopen
...
+              @sd_call_count = 0
+              return
+            end
+
+            matches = @reopen_filterable_matches.dup
 
             close
             initialize(@reopen_options)
 
+            filter(matches)
```
Comment (ledbettj) [inline lib/systemd/journal/navigable.rb:153]: It's not obvious to me that this will apply the exact same filters, depending on how they are applied.  For example if I call
```
add_filter(...)
add_conjunction
add_filter(...)
```

and the journal is re-opened, will they be applied in the same way? I'm not sure but I don't think so.

File: lib/systemd/journal/filterable.rb [hunk 2]
```diff
@@ -36,6 +36,8 @@ def filter(*conditions)
       # @param [String] value the match to search for, e.g. '/usr/bin/sshd'
       # @return [nil]
       def add_filter(field, value)
+        @reopen_filterable_matches[field] = value
```
Comment (ledbettj) [inline lib/systemd/journal/filterable.rb:39]: this would need to be cleared in `clear_filters` as well, right?

**Review by ledbettj — COMMENTED** [review]
Thanks for the PR! I have a few concerns about whether this will maintain the same filter behavior across re-opens.

If this behavior can't be maintained, it may be best to expose a `on_open`/`on_reopen` hook instead (as discussed in #108 ) to let the end-user re-apply any filters.

File: lib/systemd/journal/navigable.rb (hunk 1 above)
Comment (Watson1978) [reply lib/systemd/journal/navigable.rb:153]: Thanks. Indeed, seems that the filter using add_disjunction cannot be reapplied.
sounds on_open/on_reopen hooks are reasonable.

File: lib/systemd/journal/filterable.rb (hunk 2 above)
Comment (Watson1978) [reply lib/systemd/journal/filterable.rb:39]: You are right.

File: lib/systemd/journal/navigable.rb (hunk 1 above)
Comment (Watson1978) [reply lib/systemd/journal/navigable.rb]: Fixed with https://github.com/ledbettj/systemd-journal/pull/109/commits/2a90791304e05f7656049ae035f0735dc5f5ea41

If you find this difficult to maintain, I will consider using hooks.

**Comment by ledbettj** [comment]
> @ledbettj Can you review this PR ?
> 
> Thanks

Hi, apologies! I've been a bit busy lately. I'll try to review and test this out this weekend.

**Comment by Watson1978** [comment]
@ledbettj I know you are busy.
I hope you have time to review this PR.

Thanks!

File: lib/systemd/journal/navigable.rb [hunk 3]
```diff
@@ -137,11 +137,21 @@ def with_auto_reopen
...
           @sd_call_count += 1
           if @sd_call_count >= auto_reopen
-            cursor = self.cursor
+            begin
+              cursor = self.cursor
+            rescue
+              # Cancel the reopen process if cursor method causes 'Cannot assign requested address' error
+              @sd_call_count = 0
+              return
+            end
```
Comment (ledbettj) [inline lib/systemd/journal/navigable.rb:146]: I think this is the only part I'm not sold on -- what's the cause of this? Applying all the filters causes the result set to be empty, so it's not possible to select an entry?

Comment (ledbettj) [reply lib/systemd/journal/navigable.rb:146]: OK, I think that makes sense. Thanks!

File: lib/systemd/journal/filterable.rb [hunk 4]
```diff
@@ -88,15 +92,36 @@ def add_disjunction
...
       # @return [nil]
       def clear_filters
+        @reopen_filter_conditions = []
+
         Native.sd_journal_flush_matches(@ptr)
       end
+
+      private
+
+      def restore_filters(conditions = @reopen_filter_conditions)
```
Comment (ledbettj) [inline lib/systemd/journal/filterable.rb:111]: can we remove this default argument here? It's not used, and I think it's a little confusing at first glance.

Comment (ledbettj) [reply lib/systemd/journal/filterable.rb:111]: I'll do this after merging so it doesn't get stuck waiting for me :)

**Review by ledbettj — APPROVED** [review]
Thanks for the PR.  I apologize for taking so long to look at it.  I left one minor comment but I will address it after merge.

**Comment by Watson1978** [comment]
Thanks!

File: lib/systemd/journal/filterable.rb [hunk 5]
```diff
@@ -88,15 +92,36 @@ def add_disjunction
...
+        clear_filters
+
+        conditions.each do |condition|
+          case condition
+          when :disjunction
+            add_disjunction
+          when :conjunction
+            add_conjunction
+          else
+            add_filters(condition)
```
Comment (d-hansen) [inline lib/systemd/journal/filterable.rb:121]: I feel calling `add_filters` here is not really ideal.  Since you are appending the condition to the reopen filters array in `add_filter`, I think it would better match that use and call `add_filter` here and not rely `add_filters`.  If any changes were to occur to `add_filters` this would then break.   This really is just a method of future-proofing.   Eg, `add_filter(condition.keys.first, condition.values.first)`.   Where I do see the potential for a problem is that `add_filters` will iterate over a value that is an array, calling `add_filter` for each element of value.   However, if you are passing an array to the filter, eg `add_filter(:priority, [0,1,2,3])` then the restore operation after a re-open will result in four distinct `:priority` filters because it went through `add_filters` which iterated on the value as an array.   I did not test/confirm if that actually is what happens, but I am suspicious of that and especially because of the divergence of saving the filters in `add_filter` but then restoring them through `add_filters`.
